# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('visitDate', models.DateField()),
                ('lastDoctorvisitDate', models.DateField()),
                ('sex', models.CharField(max_length=255)),
                ('conditions', models.TextField()),
                ('canAmbulate', models.BooleanField()),
                ('canAmbulateNotes', models.CharField(max_length=1000)),
                ('hadFall', models.BooleanField()),
                ('hadFallNotes', models.CharField(max_length=1000)),
                ('hadHospitalization', models.BooleanField()),
                ('hadHospitalizationNotes', models.CharField(max_length=1000)),
                ('hadSkinIssues', models.BooleanField()),
                ('hadSkinIssuesNotes', models.CharField(max_length=1000)),
                ('isEligible', models.BooleanField()),
                ('criticalNeeds', models.CharField(max_length=1000)),
                ('serviceSchedule', models.CharField(max_length=1000)),
                ('goals', models.CharField(max_length=1000)),
                ('informalSupports', models.CharField(max_length=1000)),
                ('formalSupports', models.CharField(max_length=1000)),
                ('emergencyContacts', models.CharField(max_length=1000)),
                ('oPSD', models.BooleanField()),
                ('nutritionScore', models.SmallIntegerField()),
                ('clientIncome', models.CharField(max_length=50)),
                ('publicHealthBenefitsReviewed', models.BooleanField()),
                ('cognitiveHealthStatus', models.CharField(max_length=1000)),
                ('mentalHealthStatus', models.CharField(max_length=1000)),
                ('extraNotes', models.CharField(max_length=1000)),
                ('riskLevel', models.CharField(max_length=1000)),
                ('nextHomeVisitDate', models.DateField()),
                ('finalVisitReport', models.TextField()),
            ],
        ),
    ]
