# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import noteEntry.models


class Migration(migrations.Migration):

    dependencies = [
        ('noteEntry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seniorvisit',
            name='lastDoctorvisitDate',
        ),
        migrations.AddField(
            model_name='seniorvisit',
            name='lastDoctorVisitDate',
            field=models.DateField(default=noteEntry.models.getCurrentDateTime),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='canAmbulate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='hadFall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='hadHospitalization',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='hadSkinIssues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='isEligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='nextHomeVisitDate',
            field=models.DateField(default=noteEntry.models.getCurrentDateTime),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='oPSD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='publicHealthBenefitsReviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seniorvisit',
            name='visitDate',
            field=models.DateField(default=noteEntry.models.getCurrentDateTime),
        ),
    ]
